server:
  port: 8083

spring:
  application:
    name: portfolio-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: riskapprove

logging:
  level:
    com.riskapprove: INFO
    org.springframework: WARN

